CREATE DATABASE [Pw3-1c-IslaTesoro]
GO

USE [Pw3-1c-IslaTesoro]
GO

/****** Object:  Table [dbo].[Ubicacion]    Script Date: 24/5/2024 17:23:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ubicacion](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nchar](100) NOT NULL,
 CONSTRAINT [PK_Ubicacion] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


